language: go
go:
- 1.13.x
env:
  global:
  - COOKBOOK_REPO_PATH=https://github.com/appbricks/vpn-server/cloud/recipes
  - COOKBOOK_VERSION=0.0.5
script:
- git clone --branch=master https://github.com/mevansam/termtables.git ${GOPATH}/src/github.com/mevansam/termtables
- git clone --branch=master https://github.com/mevansam/goutils.git ${GOPATH}/src/github.com/mevansam/goutils
- git clone --branch=master https://github.com/mevansam/goforms.git ${GOPATH}/src/github.com/mevansam/goforms
- git clone --branch=master https://github.com/mevansam/gocloud.git ${GOPATH}/src/github.com/mevansam/gocloud
- git clone --branch=master https://github.com/appbricks/cloud-builder.git ${GOPATH}/src/github.com/appbricks/cloud-builder
- scripts/run-ci-build.sh
deploy:
  provider: releases
  edge: true
  api_key:
    secure: CJEV6mQIW9+gh4SwbhGlvngo3lh5ykN6wzQGju2jlFBPYQjh8FiqW5FgXocKZ3z6+HHQRZPfdXhJ8bmpt0nzZ8jLu4wEddQ/XoBa0L9+ZSpJ+KINXiYKh5itMnHS6i6eAvkklgFti30OwRe8arvh6rVjbY331VDPUF/nJsYhrpCih2uyXJtH0TmWvY/tDolFPZ6ygJvmowiSxd5DR7Oc61IGAbdBmrHJgKiMphPxmZnTXZUZ15bjU9mk/oZGg+tabstrHjBwg8V9/KTWmqu7tsVoGNOJ+NY/gentmYD8Vy40EwZpFn7Ski6z0wmusl1u3JNobPvL+3eDbOU4VljKsvWQvEzOlNwdltidQ5xMVozkthksj0UCa6MZsX9+K7/41Jx8akr5pVPn8XsZGaV0iMrzte7drY6d7nnvfn+blTKodxfI2BFZD62C5lueLvelWnrSLXmi2g8ZRhnkEVAPjMzsjPizbmL7HuCYhX0xLaocWlB8BD5toTOfxAhmGX55pJIsvxPRL94kN63bW45XAIQta1XR2ntakKLjcC8+YULiMk9rXG8lAhR9BYlGN6lnEUn1mDQM5DKfcaoFxFvfS+L+dxjtKq5Lu9+6ZZ8g9Na0KxJNtruQqzBRkAQ2MrGj2gr83ChYFxKpKDi3yrnOppB3AMV1eMSXOiHC1Z7oHU8=
  file:
  - build/releases/cb_darwin_amd64.tgz
  - build/releases/cb_linux_amd64.tgz
  - build/releases/cb_windows_amd64.tgz
  release_notes_file: doc/release-notes.md
  skip_cleanup: true
  on:
    repo: appbricks/cloud-builder-cli
    tags: true
