name: Build and stage Cloud Build CLI

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
    - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Setup default environment for build
    env:
      GOPATH: ${{ github.workspace }}/go
      CLI_SRC_PATH: ${{ github.workspace }}/go/src/github.com/appbricks/cloud-builder-cli
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      COOKBOOK_REPO_PATH: https://github.com/appbricks/vpn-server/cloud/recipes
      COOKBOOK_VERSION: 0.0.10
      ENV: dev

    steps:

    - name: Checking out cloud-builder-cli repository
      uses: actions/checkout@v2
      with:
        path: go/src/github.com/appbricks/cloud-builder-cli
        
    - name: Checking out mycloudspace-client repository
      uses: actions/checkout@v2
      with:
        repository: appbricks/mycloudspace-client
        ref: main
        path: go/src/github.com/appbricks/mycloudspace-client

    - name: Checking out cloud-builder repository
      uses: actions/checkout@v2
      with:
        repository: appbricks/cloud-builder
        ref: master
        path: go/src/github.com/appbricks/cloud-builder

    - name: Checking out gocloud repository
      uses: actions/checkout@v2
      with:
        repository: mevansam/gocloud
        ref: master
        path: go/src/github.com/mevansam/gocloud

    - name: Checking out goforms repository
      uses: actions/checkout@v2    
      with:
        repository: mevansam/goforms
        ref: master
        path: go/src/github.com/mevansam/goforms

    - name: Checking out goutils repository
      uses: actions/checkout@v2    
      with:
        repository: mevansam/goutils
        ref: master
        path: go/src/github.com/mevansam/goutils

    - name: Checking out termtables repository
      uses: actions/checkout@v2    
      with:
        repository: mevansam/termtables
        ref: master
        path: go/src/github.com/mevansam/termtables

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'

    - name: Run build
      run: |
        go version
        cd ${CLI_SRC_PATH}
        scripts/get-aws-env.sh
        scripts/build.sh :clean-all:

    - name:  Upload dev binaries to S3
      run: |
        aws s3 sync  ${CLI_SRC_PATH}/build/releases s3://${ENV}-deploy-artifacts/releases

    # - name: Stage Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     prerelease: true
    #     body: |
    #       To install, download the correct file for you system 
    #       and extract the binary to the system path or any path 
    #       that is mapped to the system's PATH variable.
    #     body_path: doc/release-notes.md
    #     files: |
    #       build/releases/cb_darwin_amd64.zip
    #       build/releases/cb_linux_amd64.zip
    #       build/releases/cb_windows_amd64.zip
    #       LICENSE
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     GITHUB_REPOSITORY: appbricks/cloud-builder-cli
