name: Build and validate Cloud Build CLI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, main, dev ]
    paths:
    - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Setup default environment for build
    env:
      COOKBOOK_REPO_PATH: https://github.com/appbricks/vpn-server/cloud/recipes
      COOKBOOK_VERSION: 0.0.10

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'

    - name: Setup Build Environment
      run: |
        go version
        pwd
        ls -al
        echo ${GOPATH}
        